import Box from '@mui/material/Box';
import Head from 'next/head'
import {Header} from "../../src/Components/Header";
import React from "react";
import {useRouter} from "next/router";
import {Restaurants} from "../../src/data/filter-data";
import {CssBaseline, Divider} from "@mui/material";
import {InfoRestaurant} from "../../src/Components/InfoRestaurant";


export default function CommentPage() {
    const router = useRouter();
    const { id } = router.query;
    const selectedRestaurant = Restaurants.find(item => item.id.toString() === id)
    const comment = selectedRestaurant && selectedRestaurant.comment
    if (selectedRestaurant === undefined || comment===undefined) {
        return null
    }
    {console.log(selectedRestaurant)}
    return (
        <>
            <Head>
                <title>{selectedRestaurant.name}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="" />
            </Head>
            <main>
                <CssBaseline/>

                <Box sx={{
                    display: 'flex',
                    flexDirection: 'column',
                    height: '100vh',
                }}>
                    <Header/>
                    <InfoRestaurant
                        image={selectedRestaurant.image}
                        name={selectedRestaurant.name}
                        address={selectedRestaurant.address}
                        rating={selectedRestaurant.rating}/>
                    <Divider/>
                    {comment.map(comment=>{
                        return  (
                           <Box>{comment}</Box>
                       )
                    },)}
                </Box>
            </main>
        </>
    )
}