import Box from '@mui/material/Box';
import Head from 'next/head'
import CssBaseline from "@mui/material/CssBaseline";
import {Header} from "../../src/Components/Header";
import {useRouter} from "next/router";
import {Restaurants} from "../../src/data/filter-data"
import Typography from "@mui/material/Typography";
import Tabs from "@mui/material/Tabs";
import Tab from "@mui/material/Tab";
import {FilterMenu} from "../../src/Components/FilterMenu";
import React from "react";
import {Divider, Paper, Rating} from "@mui/material";
import {InfoRestaurant} from "../../src/Components/InfoRestaurant";

function defaultLabelText(value : number) { return `${value} Star${value !== 1 ? 's' : ''}`; }

export default function RestaurantPage() {
    const router = useRouter();
    const { id } = router.query;
    const selectedRestaurant = Restaurants.find(item => item.id.toString() === id)
    const menu = selectedRestaurant && selectedRestaurant.menu

    if (selectedRestaurant === undefined) {
        return null
    }

    return (
        <>
            <Head>
                <title>{selectedRestaurant.name}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="" />
            </Head>
            <main>
                <CssBaseline/>

                <Box sx={{
                    display: 'flex',
                    flexDirection: 'column',
                    height: '100vh',
                }}>
                    <Header/>
                    <InfoRestaurant
                        image={selectedRestaurant.image}
                        name={selectedRestaurant.name}
                        address={selectedRestaurant.address}
                        rating={selectedRestaurant.rating}/>
                    <Divider/>
                    <FilterMenu/>

                </Box>
            </main>
        </>
    )
}