import Box from '@mui/material/Box';
import Head from 'next/head'
import CssBaseline from "@mui/material/CssBaseline";
import {Header} from "../../src/Components/Header";
import {useRouter} from "next/router";
import {Restaurants} from "../../src/data/filter-data"
import Typography from "@mui/material/Typography";
import Tabs from "@mui/material/Tabs";
import Tab from "@mui/material/Tab";
import {FilterMenu} from "../../src/Components/FilterMenu";
import React from "react";

export default function RestaurantPage() {
    const router = useRouter();
    const { id } = router.query;
    const selectedRestaurant = Restaurants.find(item => item.id.toString() === id)
    const menu = selectedRestaurant && selectedRestaurant.menu

    return (
        <>
            <Head>
                <title>{selectedRestaurant && selectedRestaurant.name}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="" />
            </Head>
            <main>
                <CssBaseline/>
                <Box sx={{
                    display: 'flex',
                    flexDirection: 'column',
                    height: '100vh',
                }}>
                    <Box>
                        <Header/>
                        <Typography fontSize={46} sx={{
                            display: 'flex',
                            px: {xs: 0, md:2},
                            justifyContent: 'center',
                            mt:2,
                            mb:2,
                        }}>
                            {selectedRestaurant && selectedRestaurant.name}
                        </Typography>
                        <FilterMenu/>
                    </Box>
                </Box>
            </main>
        </>
    )
}