import Box from '@mui/material/Box';
import Head from 'next/head'
import CssBaseline from "@mui/material/CssBaseline";
import {Header} from "../src/Components/Header";
import React from "react";
import {Accordion, AccordionDetails, AccordionSummary, Divider, Paper, TextField} from "@mui/material";
import {useSelector, useDispatch} from "react-redux";
import {
    selectAddress, selectMail,
    selectName,
    selectPhoneNumber,
    selectSurname,
    updateAddress,
    updatePhoneNumber
} from "../slices/userSlice";
import Typography from "@mui/material/Typography";
import {ExpandMore} from "@mui/icons-material";
import Grid from "@mui/material/Grid";
import Button from "@mui/material/Button";
import {flexCenter} from "../src/themes/commonThemes";


export default function Account() {
    const address = useSelector(selectAddress)
    const name = useSelector(selectName)
    const surname = useSelector(selectSurname)
    const phone = useSelector(selectPhoneNumber)
    const mail = useSelector(selectMail)

    const dispatch = useDispatch()

    return (
        <>
            <Head>
                <title>{name}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="" />
            </Head>
            <main>
                <CssBaseline/>

                <Box sx={{
                    display: 'flex',
                    flexDirection: 'column',
                    height: '100vh',
                }}>
                    <Header/>
                    <Box sx={{
                        mt: 2,
                        mb: 2,
                        mx:2,
                    }}>
                        <Typography component={"h2"} fontSize={46} color={"primary"} sx={{
                            textAlign: "center"
                        }}>
                            {name} {surname}
                        </Typography>
                        <Typography sx={{
                            textAlign: "center"
                        }}>
                            {mail}
                        </Typography>

                    </Box>
                    <Divider/>
                    <Box sx={{
                        mx:2,
                        mt:2,
                    }}>
                        <Accordion>
                            <AccordionSummary
                                expandIcon={<ExpandMore />}
                                aria-controls="panel1a-content"
                                id="panel1a-header"
                            >
                                <Typography>Détails</Typography>
                            </AccordionSummary>
                            <AccordionDetails sx={{
                                display: "flex",
                                flexDirection: "column"
                            }}>
                                <Grid container rowSpacing={2} columnSpacing={2}>
                                    <Grid item>
                                        <Typography>Nom</Typography>
                                        <TextField size={"small"} defaultValue={name}/>
                                    </Grid>
                                    <Grid item>
                                        <Typography>Prénom</Typography>
                                        <TextField size={"small"} defaultValue={surname} />
                                    </Grid>
                                    <Grid item>
                                        <Typography>Email</Typography>
                                        <TextField size={"small"} disabled defaultValue={mail}/>
                                    </Grid>
                                    <Grid item >
                                        <Typography>Téléphone</Typography>
                                        <TextField size={"small"} defaultValue={phone}/>
                                    </Grid>
                                </Grid>
                                <Button variant="outlined" sx={{
                                    mt:2
                                }}>Modifier</Button>
                            </AccordionDetails>
                        </Accordion >
                        <Accordion>
                            <AccordionSummary
                                expandIcon={<ExpandMore />}
                                aria-controls="panel2a-content"
                                id="panel2a-header"
                            >
                                <Typography>Adresses</Typography>
                            </AccordionSummary>
                            <AccordionDetails>
                                <Typography>{address}</Typography>
                            </AccordionDetails>
                        </Accordion>
                        <Accordion>
                            <AccordionSummary
                                expandIcon={<ExpandMore />}
                                aria-controls="panel3a-content"
                                id="panel3a-header">
                                <Typography>Mot de passe</Typography>
                            </AccordionSummary>
                            <AccordionDetails>
                                <Box sx={{
                                    display: "flex",
                                    flexDirection: "column"
                                }}>
                                    <Typography>
                                        Pour modifier votre mot de passe,
                                        veuillez saisir votre mot de passe actuel pour confirmer votre identité.
                                    </Typography>
                                    <TextField size={"small"} sx={{
                                        mt:2
                                    }} label={"Mot de passe"}/>
                                    <Button variant="outlined" sx={{
                                        mt:2
                                    }} >Modifier</Button>
                                </Box>
                            </AccordionDetails>
                        </Accordion>
                        <Accordion>
                            <AccordionSummary
                                expandIcon={<ExpandMore />}
                                aria-controls="panel4a-content"
                                id="panel4a-header">
                                <Typography>Suppimer définitivement le compte</Typography>
                            </AccordionSummary>
                            <AccordionDetails sx={{
                                display: "flex",
                                flexDirection: "column"
                            }}>
                                <Typography>Pour supprimer définitivement votre compte,
                                    vous devez saisir votre mot de passe.
                                    <br/>Une fois la suppression effectuée,
                                    il ne sera plus possible de réactiver votre compte.
                                </Typography>
                                <TextField size={"small"} sx={{
                                    mt:2
                                }} label={"Mot de passe"}/>
                                <Button variant="outlined" sx={{
                                    mt:2
                                }} >Modifier</Button>
                            </AccordionDetails>
                        </Accordion>
                    </Box>
                </Box>
            </main>
        </>
    )
}