import Box from '@mui/material/Box';
import Head from 'next/head'
import CssBaseline from "@mui/material/CssBaseline";
import {Header} from "../src/Components/Header";
import React from "react";
import {Accordion, AccordionDetails, AccordionSummary, Divider, TextField} from "@mui/material";
import Typography from "@mui/material/Typography";
import {ExpandMore} from "@mui/icons-material";
import Grid from "@mui/material/Grid";
import Button from "@mui/material/Button";
import {useEffect} from "react";

import {useAppDispatch, useAppSelector} from "../hooks";
import {getUser, selectUser} from "../slices/userSlice";


export default function Account() {
    const dispatch = useAppDispatch();
    const {
        data,
        pending,
        error,
    } = useAppSelector(selectUser);

    useEffect(() => {
            dispatch(getUser("e9e18a37-d0e9-438e-919d-b43640b90857"))
        }, [dispatch]
    )

    if (error) return <div>Failed to load user</div>
    if (pending) return <div>Loading</div>
    if (!data) return null

    return (
        <>
            <Head>
                <title>FaceBouffe</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href=""/>
            </Head>
            <main>
                <CssBaseline/>
                {/*
                <Box>
                    {pending && <p> Loading </p>}
                    {data && <p>{data.name}</p>}
                    {error && <p>Oops, something went wrong</p>}
                    <Button onClick={() => dispatch(getUser("818eaaea-7e91-4c98-8b11-d29411ae21fc"))}
                            disabled={pending}>
                        Nom
                    </Button>
                </Box>
                */}
                <Box sx={{
                    display: 'flex',
                    flexDirection: 'column',
                    height: '100vh',
                }}>
                    <Header/>
                    <Box sx={{
                        mt: 2,
                        mb: 2,
                        mx: 2,
                    }}>
                        <Typography component={"h2"} fontSize={46} color={"primary"} sx={{
                            textAlign: "center"
                        }}>
                            {data.name} {data.surname}
                        </Typography>
                        <Typography sx={{
                            textAlign: "center"
                        }}>
                            {data.mail}
                        </Typography>

                    </Box>
                    <Divider/>
                    <Box sx={{
                        mx: 2,
                        mt: 2,
                    }}>
                        <Accordion>
                            <AccordionSummary
                                expandIcon={<ExpandMore/>}
                                aria-controls="panel1a-content"
                                id="panel1a-header"
                            >
                                <Typography>Détails</Typography>
                            </AccordionSummary>
                            <AccordionDetails sx={{
                                display: "flex",
                                flexDirection: "column"
                            }}>
                                <Grid container rowSpacing={2} columnSpacing={2}>
                                    <Grid item>
                                        <Typography>Nom</Typography>
                                        <TextField size={"small"} defaultValue={data.name}/>
                                    </Grid>
                                    <Grid item>
                                        <Typography>Prénom</Typography>
                                        <TextField size={"small"} defaultValue={data.surname}/>
                                    </Grid>
                                    <Grid item>
                                        <Typography>Email</Typography>
                                        <TextField size={"small"} disabled defaultValue={data.mail}/>
                                    </Grid>
                                    <Grid item>
                                        <Typography>Téléphone</Typography>
                                        <TextField size={"small"} disabled defaultValue={data.phoneNumber}/>
                                    </Grid>
                                </Grid>
                                <Button variant="outlined" sx={{
                                    mt: 2
                                }}>Modifier</Button>
                            </AccordionDetails>
                        </Accordion>
                        <Accordion>
                            <AccordionSummary
                                expandIcon={<ExpandMore/>}
                                aria-controls="panel2a-content"
                                id="panel2a-header"
                            >
                                <Typography>Adresses</Typography>
                            </AccordionSummary>
                            <AccordionDetails>
                                <Typography>{data.address}</Typography>
                            </AccordionDetails>
                        </Accordion>
                        <Accordion>
                            <AccordionSummary
                                expandIcon={<ExpandMore/>}
                                aria-controls="panel3a-content"
                                id="panel3a-header">
                                <Typography>Mot de passe</Typography>
                            </AccordionSummary>
                            <AccordionDetails>
                                <Box sx={{
                                    display: "flex",
                                    flexDirection: "column"
                                }}>
                                    <Typography>
                                        Pour modifier votre mot de passe,
                                        veuillez saisir votre mot de passe actuel pour confirmer votre identité.
                                    </Typography>
                                    <TextField size={"small"} sx={{
                                        mt: 2
                                    }} label={"Mot de passe"}/>
                                    <Button variant="outlined" sx={{
                                        mt: 2
                                    }}>Modifier</Button>
                                </Box>
                            </AccordionDetails>
                        </Accordion>
                        <Accordion>
                            <AccordionSummary
                                expandIcon={<ExpandMore/>}
                                aria-controls="panel4a-content"
                                id="panel4a-header">
                                <Typography>Suppimer définitivement le compte</Typography>
                            </AccordionSummary>
                            <AccordionDetails sx={{
                                display: "flex",
                                flexDirection: "column"
                            }}>
                                <Typography>Pour supprimer définitivement votre compte,
                                    vous devez saisir votre mot de passe.
                                    <br/>Une fois la suppression effectuée,
                                    il ne sera plus possible de réactiver votre compte.
                                </Typography>
                                <TextField size={"small"} sx={{
                                    mt: 2
                                }} label={"Mot de passe"}/>
                                <Button variant="outlined" sx={{
                                    mt: 2
                                }}>Modifier</Button>
                            </AccordionDetails>
                        </Accordion>
                    </Box>
                </Box>
            </main>
        </>
    )
}