import Head from "next/head";
import styles from "../styles/Home.module.css";
import Box from "@mui/material/Box";
import CssBaseline from "@mui/material/CssBaseline";
import { Header } from "../src/Components/Header";
import { FilterTab } from "../src/Components/FilterTab";
import { RestaurantCard } from "../src/Components/RestaurantCard";
import Container from "@mui/material/Container";

export default function Home() {
  return (
    <>
      <Head>
        <title>FaceBouffe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <main className={styles.main}>
        <CssBaseline />
        <Box
          sx={{
            display: "flex",
            flexDirection: "column",
            height: "100vh",
          }}>
          <Box>
            <Header />
            <FilterTab />
            <Container
              maxWidth={"xl"}
              sx={{
                mb: 3,
                mt: 5,
              }}>
              <RestaurantCard />
            </Container>
          </Box>
        </Box>
      </main>
    </>
  );
}
