import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button'
import Box from '@mui/material/Box';
import CssBaseline from "@mui/material/CssBaseline";
import {Header} from "../src/Components/Header";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>FaceBouffe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <main className={styles.main}>
          <CssBaseline>
              <Box sx={{
                  display: 'flex',
                  flexDirection: 'column',
                  height: '100vh',
              }}>
                  <Box>
                      <Header/>
                  </Box>
              </Box>
          </CssBaseline>
      </main>
    </>
  )
}
