import Box from '@mui/material/Box';
import Head from 'next/head'
import CssBaseline from "@mui/material/CssBaseline";
import {Header} from "../src/Components/Header";
import styles from "../styles/Home.module.css";

export default function Restaurant() {
    return (
        <>
            <Head>
                <title>RestaurantName</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="" />
            </Head>
            <main className={styles.main}>
                <CssBaseline/>
                <Box sx={{
                    display: 'flex',
                    flexDirection: 'column',
                    height: '100vh',
                }}>
                    <Box>
                        <Header/>
                    </Box>
                </Box>
            </main>
        </>
    )
}